language: php

sudo: false

notifications:
    email: deploy@peter-gribanov.ru

branches:
  except:
    - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: 7.2
        - php: 7.1
        - php: 7.0
        - php: 5.6
        - php: 5.5
        - php: 5.5
          env: SYMFONY_VERSION=2.7.*
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*
        - php: 5.5
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.1.* PHPUNIT_VERSION=5.7.*
        - php: 5.5
          env: DOCTRINE_VERSION=2.4.*
        - php: 5.5
          env: DOCTRINE_VERSION=2.5.*
        - php: 7.2
          env: DOCTRINE_VERSION=2.6.*
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge
    allow_failures:
        - php: hhvm

before_install:
    - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then echo 'xdebug.enable = on' >> /etc/hhvm/php.ini; fi
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --dev --no-update; fi;
    - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/orm:${DOCTRINE_VERSION}" --dev --no-update; fi;
    - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update; fi;
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/phpunit/phpunit/phpunit --coverage-clover build/coverage-clover.xml

after_script:
    - vendor/scrutinizer/ocular/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/satooshi/php-coveralls/bin/coveralls -v -c .coveralls.yml
