services:
    domain_event.bus.listener_locator:
        class: GpsLab\Domain\Event\Bus\Bus # BC: use deprecated class
        arguments: [ '@domain_event.locator' ]
        public: false

    domain_event.bus.queue:
        class: GpsLab\Domain\Event\Bus\QueueEventBus
        arguments: [ '@domain_event.queue', '@domain_event.bus.listener_locator' ]
        public: false
