services:
    domain_event.bus.listener_located:
        class: GpsLab\Domain\Event\Bus\ListenerLocatedEventBus
        arguments: [ '@domain_event.locator' ]
        public: false

    domain_event.bus.queue:
        class: GpsLab\Domain\Event\Bus\QueueEventBus
        arguments: [ '@domain_event.queue' ]
        public: false
