services:
    domain_event.locator.symfony:
        class: GpsLab\Domain\Event\Listener\Locator\SymfonyContainerEventListenerLocator
        calls:
            - [ setContainer, [ '@service_container' ] ]
        public: false

    domain_event.locator.container:
        class: GpsLab\Domain\Event\Listener\Locator\ContainerEventListenerLocator
        arguments: [ '@service_container' ]
        public: false

    domain_event.locator.direct_binding:
        class: GpsLab\Domain\Event\Listener\Locator\DirectBindingEventListenerLocator
        public: false
