services:
    domain_event.name_resolver.event_class_last_part:
        class: GpsLab\Domain\Event\NameResolver\EventClassLastPartResolver
        public: false

    domain_event.name_resolver.event_class:
        class: GpsLab\Domain\Event\NameResolver\EventClassResolver
        public: false

    domain_event.name_resolver.named_event:
        class: GpsLab\Domain\Event\NameResolver\NamedEventResolver
        public: false
