services:
    domain_event.publisher:
        class: GpsLab\Bundle\DomainEvent\Event\Listener\DomainEventPublisher
        arguments: [ '@domain_event.bus', ~ ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
