name: Test

on: [push, pull_request ]

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony }} + Doctrine ORM ${{ matrix.doctrine }}
        runs-on: ubuntu-latest
        continue-on-error: false

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php: '5.5'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '4.8.*'
                    - php: '5.6'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '4.8.*'
                    - php: '7.0'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '4.8.*'
                    - php: '7.1'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '6.5.*'
                    - php: '7.2'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '6.5.*'
                    - php: '7.3'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '2.8.*'
                      doctrine: '2.4.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '3.4.*'
                      doctrine: '2.6.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '4.4.*'
                      doctrine: '2.6.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '5.*'
                      doctrine: '2.7.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '4.4.*'
                      doctrine: '2.7.*'
                      phpunit: '6.5.*'
                    - php: '7.4'
                      symfony: '4.4.*'
                      doctrine: '2.8.*'
                      phpunit: '6.5.*'
#                    # require PHPUnit >= 8.5.12
#                    - php: '8.0'
#                      symfony: '5.*'
#                      doctrine: '2.*'

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
                  tools: composer:v2

            - name: Install Symfony
              run: composer require symfony/symfony:"${{ matrix.symfony }}" --no-update

            - name: Install Doctrine
              run: composer require doctrine/orm:"${{ matrix.doctrine }}" --no-update

            - name: Install PHPUnit
              run: composer require phpunit/phpunit:"${{ matrix.phpunit }}" --no-update

            - name: "Install Composer dependencies (highest)"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "highest"
                  composer-options: "--prefer-dist --prefer-stable"

            - name: Run Tests
              run: vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

            - name: Send coverage results to Scrutinizer CI
              run: |
                wget https://scrutinizer-ci.com/ocular.phar
                php ocular.phar code-coverage:upload --format=php-clover build/coverage-clover.xml

            - name: Send coverage results to Coveralls
              env:
                COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                COVERALLS_PARALLEL: true
                COVERALLS_FLAG_NAME: 'PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony }} + Doctrine ORM ${{ matrix.doctrine }}'
              run: |
                composer global require php-coveralls/php-coveralls
                php-coveralls --coverage_clover=build/coverage-clover.xml -v -c .coveralls.yml
